Add support for 'sslmode' and 'options' to be passed on the connection string
cockroachdb/django-cockroachdb pull request #268
Opened 2022-10-21 11:11 UTC by aviddiviner

The latest [Cockroach docs for Django](https://www.cockroachlabs.com/docs/stable/connect-to-the-database.html?filters=python&filters=django) advise setting connection information like so:

```
DATABASES = {
    'default': {
        'ENGINE': 'django_cockroachdb',
        'NAME': '{database}',
        'USER': '{username}',
        'PASSWORD': '{password}',
        'HOST': '{host}',
        'PORT': '{port}',
        'OPTIONS': {
            'sslmode': 'verify-full',
            'options': '--cluster={routing-id}'
        },
    },
}
```

This currently doesn't work, as the `OPTIONS` are never passed to the connection string. This pull request addresses that and allows connections to CockroachDB Serverless, that requires a `--cluster` routing key.

2022-10-21 21:16 UTC, rafiss requested changes
thanks for your contribution!

would you mind updating the commit and PR to clarify that this is specifically for using Django to connect with the `cockroach sql` shell?

most of the code lgtm, but i'd like @timgraham to weigh in as well

2022-10-21 21:16 UTC, rafiss commented on django_cockroachdb/client.py
>          else:
i think it's best to be explicit. can we make this `elif sslmode == "disable" || sslmode == ""`, and then the `else` branch should show an error that an invalid sslmode was chosen

2022-10-21 21:16 UTC, rafiss commented on django_cockroachdb/client.py
> +            suffix = '?' + urllib.parse.urlencode(url_params) if url_params else ''
as-is, the `options` params will only be passed through if a password was used

i wonder if we should change this so COCKROACH_URL is _always_ used

2022-10-21 21:55 UTC, aviddiviner commented on django_cockroachdb/client.py
>          else:
Sure, I'll add some more conditional checks for `sslmode` 👍

2022-10-21 21:56 UTC, aviddiviner commented on django_cockroachdb/client.py
>          else:
It's worth noting though, that currently we don't raise any errors on bad params, so I'm not sure if we want to change that behaviour. 🤷

2022-10-21 22:07 UTC, timgraham commented on django_cockroachdb/client.py
>          else:
Correct. I expect the server raises an error for invalid options.

2022-10-21 22:49 UTC, aviddiviner commented on django_cockroachdb/client.py
>          else:
I've made the change. It will pass it through now at least in the options if it is `'disable'`. And raise on any bad value.

2022-10-21 22:49 UTC, aviddiviner commented on django_cockroachdb/client.py
> +            suffix = '?' + urllib.parse.urlencode(url_params) if url_params else ''
I'm doing so now. 👍

2022-10-21 22:54 UTC, aviddiviner commented on django_cockroachdb/client.py
>          else:
Okay, I actually made a little tweak. I don't like raising on the value explicitly, it doesn't seem to fit in with the rest of the code, but I am always passing the value on through to `cockroach` now, so it will error out there. And I'm handling `sslmode=disable` nicely.

2022-10-21 23:03 UTC, aviddiviner commented on django_cockroachdb/client.py
> +        if sslmode in ["allow", "prefer", "require", "verify-ca", "verify-full", "disable"]:
I could just change this to `if sslmode:` so I just pass whatever value we get. Let me know if you prefer that @rafiss.

2022-10-21 23:05 UTC, aviddiviner commented on django_cockroachdb/client.py
> +        if sslmode in ["allow", "prefer", "require", "verify-ca", "verify-full", "disable"]:
You know what, I prefer that actually. Makes the code more future proof, because the value can be handled by cockroach.

2022-10-21 23:08 UTC, aviddiviner commented on django_cockroachdb/client.py
> +        if sslmode in ["allow", "prefer", "require", "verify-ca", "verify-full", "disable"]:
Well, I suppose they could introduce other SSL modes that we want `insecure` to be `True` for. I don't know. Anyway, it is what it is for now, I'll leave it over to you. 🤷

2022-10-22 02:19 UTC, timgraham commented
Thanks. I'd prefer if the change to always use `COCKROACH_URL` be a separate commit and/or PR that precedes the new feature so as to (as much as possible) not mix refactors and new features. If you want to me to do that, I don't mind. I'm going to try to write some tests (and will do manual testing also).

As the patch stands now, I'm guessing there's no need to add `db`, `user`, `host`, and `port` to `args` since `COCKROACH_URL` is always set? Can `sslrootcert` and `insecure` be part of `url_params` instead of `args` too?

Have you tested the patch to confirm that `--cluster={routing-id}` works? I've only tested local connections in the past.

2022-10-22 02:20 UTC, timgraham commented on django_cockroachdb/client.py
> +        if sslmode in ["allow", "prefer", "require", "verify-ca", "verify-full", "disable"]:
At first glance, `if sslmode:` looks nice to me.

2022-10-24 20:04 UTC, aviddiviner commented
Okay, I've tried one last time now, to keep my changes pretty minimal and pretty close to the current behaviour, while still fixing the original issue – allowing us to use this with CockroachDB Serverless – and addresses most of the comments. I think other changes can happen in subsequent PRs. At least this is an improvement without changing any current behaviour.

@timgraham @rafiss Can you take a last look please?

2022-10-24 20:05 UTC, aviddiviner commented
> Have you tested the patch to confirm that `--cluster={routing-id}` works? I've only tested local connections in the past.

Yes, 100%. That's the reason for this PR. I'm using this in production as of now.

2022-10-26 17:14 UTC, rafiss commented on django_cockroachdb/client.py
> +            query = '?' + urllib.parse.urlencode(url_params) if url_params else ''
it still seems non-ideal that `options` are only passed through if a `password` is given. should we change the condition to `if password or options`?

2022-10-26 17:15 UTC, timgraham commented on django_cockroachdb/client.py
> +            query = '?' + urllib.parse.urlencode(url_params) if url_params else ''
I'm going to clean this up in a separate commit.

2022-10-26 17:21 UTC, aviddiviner commented on django_cockroachdb/client.py
> +            query = '?' + urllib.parse.urlencode(url_params) if url_params else ''
Okay yeah, I agree. I put in `or url_params`. I also squashed all the commits on this branch, so it's only a single commit merge.

2022-10-26 17:32 UTC, timgraham commented on django_cockroachdb/client.py
> +            query = '?' + urllib.parse.urlencode(url_params) if url_params else ''
Is `{user}:` (with a blank password) a valid URL? Anyway, you don't need to spend more time on this unless you want to take up my plan to do the refactor of always passing COCKRAOCH_URL in one commit, then add the new functionality in a second. That's my plan. I started writing some tests yesterday.

2022-10-26 17:33 UTC, aviddiviner commented on django_cockroachdb/client.py
> +            query = '?' + urllib.parse.urlencode(url_params) if url_params else ''
I'd like you guys to merge this if possible. I don't really want to refactor, just want a package that actually works with CockroachDB Serverless.

2022-10-26 17:41 UTC, timgraham commented on django_cockroachdb/client.py
> +            query = '?' + urllib.parse.urlencode(url_params) if url_params else ''
No worries, it won't delay this. The next release of this package is coming after CockroachDB 22.2 is released.

2022-10-27 00:58 UTC, timgraham commented on django_cockroachdb/client.py
> +            query = '?' + urllib.parse.urlencode(url_params) if url_params else ''
To answer my concern a couple comments above, a connection URL like `username:` (with no password) works fine and so does a colon followed by an empty port, so although the URL looks a little funny, there's no need to omit those colons if password or port are empty.

David, could you please check and test https://github.com/cockroachdb/django-cockroachdb/pull/269. After reviews, I'll merge the first commit in that PR and then move the second commit to this PR for that merge.

Thank you for your contribution, and sorry for the back and forth.

p.s. I've written [some unit tests](https://gist.github.com/timgraham/f9d21e09eb1d2b22db4b0dd9e7120458) to make future work here easier, although I need to figure out how I can include them in this repo while also having the Django test suite pick them up.

2022-11-02 17:10 UTC, timgraham approved these changes

2022-11-02 18:36 UTC, merged